source "https://rubygems.org"

gem "omnibus", git: "https://github.com/chef/omnibus.git", tag: 'v5.6.10'
gem 'omnibus-software', git: 'https://github.com/Altiscale/omnibus-software.git', branch: 'master-altiscale'
gem 'artifactory'
gem 'ohai', '< 14'
gem "pedump"
gem 'thor', '< 0.19.2'

# This development group is installed by default when you run `bundle install`,
# but if you are using Omnibus in a CI-based infrastructure, you do not need
# the Test Kitchen-based build lab. You can skip these unnecessary dependencies
# by running `bundle install --without development` to speed up build times.
group :development do
  # Use Berkshelf for resolving cookbook dependencies
  gem "berkshelf", "~> 4.0"

  # Use Test Kitchen with Vagrant for converging the build environment
  gem "test-kitchen",    "~> 1.13"
  gem "kitchen-vagrant", "~> 0.19.0"
  gem "winrm-fs", "~> 1.0"
  gem "pry"
  gem "pry-byebug"
  gem "pry-stack_explorer"
end
